pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/Eb1n-Babu/jenkins.git', branch: 'main'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'cd jenkins && python -m unittest anagram.test_anagram'
            }
        }
    }
}