pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/Eb1n-Babu/jenkins.git', branch: 'main'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'python -m unittest jenkins\\anagram\\test_anagram.py'
            }
        }
    }
}