pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/Eb1n-Babu/jenkins.git', branch: 'main'
            }
        }

        stage('Run Unit Tests') {
            steps {
                bat 'python -m unittest palindrome/test_palindrome.py'
            }
        }
    }
}