pipeline {
	agent any
	stages {
		stage("checkout git"){
			steps{
				git url: 'https://github.com/Eb1n-Babu/jenkins.git', branch: 'main'
			}
		}
	    stage("run django test"){
			steps{
				bat """
				python -m venv venv
                venv\\Scripts\\pip install -r requirements.txt
                venv\\Scripts\\python manage.py test
                """
			}
		}
	}
}