pipeline {
	agent any
	stages {
		stage("checkout git"){
			steps{
				git url: 'https://github.com/Eb1n-Babu/jenkins.git', branch: 'main'
			}
		}
	    stage("run django test"){
			steps{
				bat """
				cd django_app
				C:\\Users\\ebinb\\AppData\\Local\\Programs\\Python\\Python313\\python.exe -m venv venv
                venv\\Scripts\\pip install -r requirements.txt
                venv\\Scripts\\python manage.py test
                """
			}
		}
		stage("docker"){
			steps{
				bat """
				cd django_app
				docker build -t django:wip .
				docker run -d --name djangocontainer -p 8000:8000 django:wip
				"""
			}
		}
	}
}