pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/Eb1n-Babu/jenkins.git', branch: 'main'
            }
        }

        stage('Run Unit Tests') {
            steps {
                bat 'cd prime_check && python -m unittest test_prime.py'
            }
        }
    }
}